name = "MonteCarlo"
uuid = "07692032-97b4-4f8d-80d7-e18df88d31a9"
authors = ["Leonardo Galliano <leonardo.galliano@espci.fr>", "Romain Simon <romain.simon@umontpellier.fr>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
EnzymeExt = "Enzyme"
ZygoteExt = "Zygote"

[compat]
Enzyme = "0.12.36"
julia = "1.9"

[extras]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Coverage", "ComponentArrays", "DelimitedFiles", "SafeTestsets", "Enzyme", "Zygote"]
